/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package finalproject_2ndyear;

import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.intellijthemes.FlatGradiantoDeepOceanIJTheme;
import com.formdev.flatlaf.intellijthemes.FlatGradiantoNatureGreenIJTheme;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class CreateAccPage extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CreateAccPage.class.getName());

    /**
     * Creates new form CreateAccountPage
     */
    public CreateAccPage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        confirmpass = new javax.swing.JPasswordField();
        backB = new javax.swing.JButton();
        createAcc = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel2.setText("Confirm password");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 450, -1, -1));

        jLabel3.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel3.setText("Username");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, -1, -1));

        jLabel4.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        jLabel4.setText("Password");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 360, -1, -1));

        username.setBackground(new java.awt.Color(255, 255, 255));
        username.setFont(new java.awt.Font("Montserrat", 0, 24)); // NOI18N
        username.setForeground(new java.awt.Color(0, 0, 0));
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 340, 50));

        password.setBackground(new java.awt.Color(255, 255, 255));
        password.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        password.setForeground(new java.awt.Color(0, 0, 0));
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 340, 50));

        confirmpass.setBackground(new java.awt.Color(255, 255, 255));
        confirmpass.setFont(new java.awt.Font("Montserrat", 0, 18)); // NOI18N
        confirmpass.setForeground(new java.awt.Color(0, 0, 0));
        getContentPane().add(confirmpass, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 470, 340, 50));

        backB.setFont(new java.awt.Font("Montserrat", 0, 14)); // NOI18N
        backB.setForeground(new java.awt.Color(255, 255, 255));
        backB.setText("BACK");
        backB.setBorderPainted(false);
        backB.setContentAreaFilled(false);
        backB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBActionPerformed(evt);
            }
        });
        getContentPane().add(backB, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 590, 190, 40));

        createAcc.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        createAcc.setForeground(new java.awt.Color(255, 255, 255));
        createAcc.setText("CREATE");
        createAcc.setBorderPainted(false);
        createAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccActionPerformed(evt);
            }
        });
        getContentPane().add(createAcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 540, 190, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/BG FOR PAGES/Create Acc Page.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBActionPerformed
        LoginPage showThis = new LoginPage();
        showThis.show();
        dispose();
    }//GEN-LAST:event_backBActionPerformed

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void createAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccActionPerformed
        String accUser = username.getText().trim();
        String userPass = new String(password.getPassword()).trim();
        String userPass2 = new String(confirmpass.getPassword()).trim();

        // Validate inputs
        if (accUser.isEmpty() || userPass.isEmpty() || userPass2.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please input in all fields");
            return;
        }

        if (!userPass.equals(userPass2)) {
            JOptionPane.showMessageDialog(this, "It seems that your password doesn't match, please try again.");
            return;
        }

        PreparedStatement checkPst = null;
        ResultSet rs = null;
        PreparedStatement pst = null;

        try {
            Connection appConnection = Connector_MyMovieSeriesApp.getConnection();

            // CHECK IF USERNAME EXISTS
            String checkSql = "SELECT COUNT(*) AS count FROM appaccounts WHERE accountName = ?";
            checkPst = appConnection.prepareStatement(checkSql);
            checkPst.setString(1, accUser);
            rs = checkPst.executeQuery();

            if (rs.next() && rs.getInt("count") > 0) {
                JOptionPane.showMessageDialog(this,
                        "Account already exists. Please choose a different username.");
                return;
            }

            // INSERT NEW ACCOUNT
            String insertSql = "INSERT INTO appaccounts (accountName, accPass) VALUES (?, ?)";
            pst = appConnection.prepareStatement(insertSql);
            pst.setString(1, accUser);
            pst.setString(2, userPass);
            pst.executeUpdate();

            // Clear fields
            username.setText("");
            password.setText("");
            confirmpass.setText("");

            JOptionPane.showMessageDialog(this, "User Account Added Successfully");
            LoginPage showThis = new LoginPage();
            showThis.show();
            dispose();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "SQL Error: " + e.getMessage());
            e.printStackTrace();
        } finally {
            // Close resources but NOT the connection (it's a singleton)
            try { if (rs != null) rs.close(); } catch (SQLException e) { e.printStackTrace(); }
            try { if (checkPst != null) checkPst.close(); } catch (SQLException e) { e.printStackTrace(); }
            try { if (pst != null) pst.close(); } catch (SQLException e) { e.printStackTrace(); }
        }

    }//GEN-LAST:event_createAccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        FlatGradiantoDeepOceanIJTheme.setup();
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CreateAccPage().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backB;
    private javax.swing.JPasswordField confirmpass;
    private javax.swing.JButton createAcc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
